### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Kirvx**
Hi :)

If you want a french translation in a next release, here it is.

### CODE REVIEW

**Comment by voisine** [comment]
fantastic :)

**Comment by voisine** [comment]
If you have an interest, you could also create a french word list for bip39, so recovery phrases can also be in french:

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by Kirvx** [comment]
@voisine I would like but i'm not dev and I don't have the skills for scripting as Y75QMO did to check his work on the spanish wordlist https://github.com/Y75QMO/Tests-for-BIP39-Spanish-wordlist/blob/master/test_BIP39_Spanish_wordlist.py :/

**Comment by voisine** [comment]
Those scripts aren't really necessary, I didn't do anything like that when I did the English list. I just found a corpus of the 10000 most common English words and then sorted my own list alphabetically with the "sort" command line tool to make sure the first four letters were unique for each of the words picked.

**Comment by Kirvx** [comment]
@voisine I'm on it, give me a week :)

**Comment by Kirvx** [comment]
@voisine Hi :)
The french wordlist is almost done, but I applied a bunch of restrictions (I want an faultless wordlist) like the spanish wordlist using only my very noob skills on regex, and kow I need to check if there are similar words with 1 letter of difference with a script or a tool (almost impossible without).
So if you have extra time, you can help me on that :)

**Comment by voisine** [comment]
Excellent, send me over the word list and I'll try to find some time this
weekend to get you some scripts. I have been called an idiot savant where
regular expressions are concerned. :)


Aaron Voisine
co-founder and CEO
breadwallet.com

**Comment by Kirvx** [comment]
@voisine Thanks have you an e-mail? :)

**Comment by voisine** [comment]
derp, I didn't notice I was responding to the github email issue notification. 

voisine@gmail.com

**Pull request merged**
