### PR TITLE
Cancel exchange rate updates in background

### PR DESCRIPTION
**Pull request by sammichaels**
When moving to the background, cancel exchange rate updates to prevent
unnecessary traffic.  When moving back to the foreground, restart the
updates.

### CODE REVIEW

**Comment by voisine** [comment]
I'm curious if you're seeing ongoing network traffic while the app is backgrounded? I believe the app is supposed to be paused while backgrounded unless a background task is explicitly scheduled or during a background network fetch triggered by the OS.

Also it might be cleaner to just check if the app is backgrounded and return in [BRWalletManager updateExchangeRate] line 803, rather than observing background and foreground notifications.

**Comment by sammichaels** [comment]
Here is the debug log:

2015-05-03 21:04:18.248 breadwallet[10731:5750505] Reachability Flag Status: -R -----l- networkStatusForFlags
2015-05-03 21:04:18.502 breadwallet[10731:5750505] exchange rate updated to $238.78/ƀ 1,000,000
2015-05-03 21:04:31.188 breadwallet[10731:5750505] !BACKGROUND
2015-05-03 21:04:31.195 breadwallet[10731:5751248] 162.243.132.6:18333 disconnected
2015-05-03 21:04:31.196 breadwallet[10731:5754307] 54.84.126.154:18333 disconnected
2015-05-03 21:04:31.196 breadwallet[10731:5756552] 54.191.125.127:18333 disconnected
2015-05-03 21:05:18.245 breadwallet[10731:5750505] Reachability Flag Status: -R -----l- networkStatusForFlags
2015-05-03 21:05:18.511 breadwallet[10731:5750505] exchange rate updated to $238.78/ƀ 1,000,000
2015-05-03 21:06:18.242 breadwallet[10731:5750505] Reachability Flag Status: -R -----l- networkStatusForFlags
2015-05-03 21:06:18.421 breadwallet[10731:5750505] exchange rate updated to $238.78/ƀ 1,000,000

You can see where the peers disconnect from going to the background, but the exchange rate updates continue to happen.  Maybe it's a non-issue because the simulator isn't suspending the app, but I figured cleaning up that repeating function on moving to background was worth a look.

**Comment by voisine** [comment]
Yes that's definitely something you want to test on an actual device. Also worth noting is that we want the exchange rate to update during background network fetches. The OS turns on the radios and does all the background fetches for multiple apps at once to save battery so we want to take advantage and get the latest market rates.

**Comment by sammichaels** [comment]
Tested this on an actual device and the behavior is definitely different.  On a real device it suspends the app and essentially "pauses" that function.  Looks to be a non-issue.

**Comment by voisine** [comment]
Thanks for testing, I hadn't actually verified that was the behavior yet.

**Pull request closed without merging**
